// <copyright file="SettingsData.cs" company="PublicDomain.is">
//     CC0 1.0 Universal (CC0 1.0) - Public Domain Dedication
//     https://creativecommons.org/publicdomain/zero/1.0/legalcode
// </copyright>
// <auto-generated />

namespace PublicDomain
{
    // Directives
    using System.Collections.Generic;
    using System.Drawing;

    /// <summary>
    /// Urlister settings.
    /// </summary>
    public class SettingsData
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="T:PublicDomain.SettingsData"/> class.
        /// </summary>
        public SettingsData()
        {
            // Parameterless constructor
        }

        /// <summary>
        /// Gets or sets the keyword.
        /// </summary>
        /// <value>The keyword.</value>
        public string Keyword { get; set; } = "publicdomain";

        /// <summary>
        /// Gets or sets the checked target browser.
        /// </summary>
        /// <value>The checked target browser.</value>
        public string CheckedTargetBrowser { get; set; }

        /// <summary>
        /// Gets or sets the search terms list.
        /// </summary>
        /// <value>The search terms list.</value>
        public List<string> SearchTermsList { get; set; } = new List<string>();

        /// <summary>
        /// Gets or sets the search engines list.
        /// </summary>
        /// <value>The search engines list.</value>
        public List<string> SearchEnginesList { get; set; } = new List<string>();

        /// <summary>
        /// Gets or sets a value indicating whether this <see cref="T:PublicDomain.SettingsData"/> always on top.
        /// </summary>
        /// <value><c>true</c> if always on top; otherwise, <c>false</c>.</value>
        public List<string> CheckedOptionsList { get; set; }
    }
}